function(vcpkg_get_windows_sdk out_var)
    if("$ENV{WindowsSDKVersion}" MATCHES [[^([0-9.]*)(\\|/)?$]])
        set("${out_var}" "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "ENV{WindowsSDKVersion} 的格式不符合预期 ($ENV{WindowsSDKVersion})")
    endif()
endfunction()
